[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Handle redirects for authentication flows
[[redirects]]
  from = "/auth/reset-callback"
  to = "/.netlify/functions/next_auth_callback"
  status = 200
  force = true

[[redirects]]
  from = "/auth/reset-password"
  to = "/auth/reset-password"
  status = 200
  force = true 